### ISSUE TITLE
Offer help with 3D models

### ISSUE THREAD

**Issue by PCB-Tech-eu** [boelle/326298-Rev-A-Kicad#2]

**Comment by bwack** [comment]
I'd like to try this in my KU-14194HB C64 motherboard project. Do I need to convert the STEP files or does KiCad load them if I add them as a 3D package ?

**Comment by PCB-Tech-eu** [comment]
KiCad can use STEP files directly without conversion. Simply select and position it in the Footprint Editor and you're done.

**Comment by PCB-Tech-eu** [comment]
Since apparently the project doesn't need any help with the 3D models, I withdraw my free help offer!

**Comment by bwack** [comment]
If you like to help me instead, I have a very similar repo that i'm working on
https://github.com/bwack/KU-14194HB-RevB-KiCad
